/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PoliticaRouteImport } from './routes/politica'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssinaturaRouteImport } from './routes/assinatura'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedWhatsappRouteImport } from './routes/_authenticated/whatsapp'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedTarefasRouteImport } from './routes/_authenticated/tarefas'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedFunilRouteImport } from './routes/_authenticated/funil'
import { Route as AuthenticatedEvaRouteImport } from './routes/_authenticated/eva'
import { Route as AuthenticatedEmpresasRouteImport } from './routes/_authenticated/empresas'
import { Route as AuthenticatedDisparosRouteImport } from './routes/_authenticated/disparos'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedCadenciasRouteImport } from './routes/_authenticated/cadencias'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedCrmIndexRouteImport } from './routes/_authenticated/crm.index'
import { Route as AuthenticatedCrmIdRouteImport } from './routes/_authenticated/crm.$id'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicMetaWebhookRouteImport } from './routes/api/public/meta/webhook'
import { Route as ApiPublicHooksCampaignRunRouteImport } from './routes/api/public/hooks/campaign-run'
import { Route as ApiPublicHooksCadenceRunRouteImport } from './routes/api/public/hooks/cadence-run'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaRoute = PoliticaRouteImport.update({
  id: '/politica',
  path: '/politica',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinaturaRoute = AssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWhatsappRoute = AuthenticatedWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTarefasRoute = AuthenticatedTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFunilRoute = AuthenticatedFunilRouteImport.update({
  id: '/funil',
  path: '/funil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEvaRoute = AuthenticatedEvaRouteImport.update({
  id: '/eva',
  path: '/eva',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmpresasRoute = AuthenticatedEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDisparosRoute = AuthenticatedDisparosRouteImport.update({
  id: '/disparos',
  path: '/disparos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCadenciasRoute = AuthenticatedCadenciasRouteImport.update({
  id: '/cadencias',
  path: '/cadencias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmIndexRoute = AuthenticatedCrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedCrmRoute,
} as any)
const AuthenticatedCrmIdRoute = AuthenticatedCrmIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedCrmRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMetaWebhookRoute = ApiPublicMetaWebhookRouteImport.update({
  id: '/api/public/meta/webhook',
  path: '/api/public/meta/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksCampaignRunRoute =
  ApiPublicHooksCampaignRunRouteImport.update({
    id: '/api/public/hooks/campaign-run',
    path: '/api/public/hooks/campaign-run',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCadenceRunRoute =
  ApiPublicHooksCadenceRunRouteImport.update({
    id: '/api/public/hooks/cadence-run',
    path: '/api/public/hooks/cadence-run',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/assinatura': typeof AssinaturaRoute
  '/auth': typeof AuthRoute
  '/politica': typeof PoliticaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/cadencias': typeof AuthenticatedCadenciasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/crm': typeof AuthenticatedCrmRouteWithChildren
  '/disparos': typeof AuthenticatedDisparosRoute
  '/empresas': typeof AuthenticatedEmpresasRoute
  '/eva': typeof AuthenticatedEvaRoute
  '/funil': typeof AuthenticatedFunilRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/crm/$id': typeof AuthenticatedCrmIdRoute
  '/crm/': typeof AuthenticatedCrmIndexRoute
  '/api/public/hooks/cadence-run': typeof ApiPublicHooksCadenceRunRoute
  '/api/public/hooks/campaign-run': typeof ApiPublicHooksCampaignRunRoute
  '/api/public/meta/webhook': typeof ApiPublicMetaWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/assinatura': typeof AssinaturaRoute
  '/auth': typeof AuthRoute
  '/politica': typeof PoliticaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/cadencias': typeof AuthenticatedCadenciasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/disparos': typeof AuthenticatedDisparosRoute
  '/empresas': typeof AuthenticatedEmpresasRoute
  '/eva': typeof AuthenticatedEvaRoute
  '/funil': typeof AuthenticatedFunilRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/': typeof AuthenticatedIndexRoute
  '/crm/$id': typeof AuthenticatedCrmIdRoute
  '/crm': typeof AuthenticatedCrmIndexRoute
  '/api/public/hooks/cadence-run': typeof ApiPublicHooksCadenceRunRoute
  '/api/public/hooks/campaign-run': typeof ApiPublicHooksCampaignRunRoute
  '/api/public/meta/webhook': typeof ApiPublicMetaWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/assinatura': typeof AssinaturaRoute
  '/auth': typeof AuthRoute
  '/politica': typeof PoliticaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/cadencias': typeof AuthenticatedCadenciasRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRouteWithChildren
  '/_authenticated/disparos': typeof AuthenticatedDisparosRoute
  '/_authenticated/empresas': typeof AuthenticatedEmpresasRoute
  '/_authenticated/eva': typeof AuthenticatedEvaRoute
  '/_authenticated/funil': typeof AuthenticatedFunilRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/tarefas': typeof AuthenticatedTarefasRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/whatsapp': typeof AuthenticatedWhatsappRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/crm/$id': typeof AuthenticatedCrmIdRoute
  '/_authenticated/crm/': typeof AuthenticatedCrmIndexRoute
  '/api/public/hooks/cadence-run': typeof ApiPublicHooksCadenceRunRoute
  '/api/public/hooks/campaign-run': typeof ApiPublicHooksCampaignRunRoute
  '/api/public/meta/webhook': typeof ApiPublicMetaWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assinatura'
    | '/auth'
    | '/politica'
    | '/reset-password'
    | '/agenda'
    | '/cadencias'
    | '/configuracoes'
    | '/crm'
    | '/disparos'
    | '/empresas'
    | '/eva'
    | '/funil'
    | '/historico'
    | '/tarefas'
    | '/usuarios'
    | '/whatsapp'
    | '/crm/$id'
    | '/crm/'
    | '/api/public/hooks/cadence-run'
    | '/api/public/hooks/campaign-run'
    | '/api/public/meta/webhook'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/assinatura'
    | '/auth'
    | '/politica'
    | '/reset-password'
    | '/agenda'
    | '/cadencias'
    | '/configuracoes'
    | '/disparos'
    | '/empresas'
    | '/eva'
    | '/funil'
    | '/historico'
    | '/tarefas'
    | '/usuarios'
    | '/whatsapp'
    | '/'
    | '/crm/$id'
    | '/crm'
    | '/api/public/hooks/cadence-run'
    | '/api/public/hooks/campaign-run'
    | '/api/public/meta/webhook'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/_authenticated'
    | '/assinatura'
    | '/auth'
    | '/politica'
    | '/reset-password'
    | '/_authenticated/agenda'
    | '/_authenticated/cadencias'
    | '/_authenticated/configuracoes'
    | '/_authenticated/crm'
    | '/_authenticated/disparos'
    | '/_authenticated/empresas'
    | '/_authenticated/eva'
    | '/_authenticated/funil'
    | '/_authenticated/historico'
    | '/_authenticated/tarefas'
    | '/_authenticated/usuarios'
    | '/_authenticated/whatsapp'
    | '/_authenticated/'
    | '/_authenticated/crm/$id'
    | '/_authenticated/crm/'
    | '/api/public/hooks/cadence-run'
    | '/api/public/hooks/campaign-run'
    | '/api/public/meta/webhook'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AssinaturaRoute: typeof AssinaturaRoute
  AuthRoute: typeof AuthRoute
  PoliticaRoute: typeof PoliticaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicHooksCadenceRunRoute: typeof ApiPublicHooksCadenceRunRoute
  ApiPublicHooksCampaignRunRoute: typeof ApiPublicHooksCampaignRunRoute
  ApiPublicMetaWebhookRoute: typeof ApiPublicMetaWebhookRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica': {
      id: '/politica'
      path: '/politica'
      fullPath: '/politica'
      preLoaderRoute: typeof PoliticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinatura': {
      id: '/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AssinaturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/whatsapp': {
      id: '/_authenticated/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AuthenticatedWhatsappRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tarefas': {
      id: '/_authenticated/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof AuthenticatedTarefasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/funil': {
      id: '/_authenticated/funil'
      path: '/funil'
      fullPath: '/funil'
      preLoaderRoute: typeof AuthenticatedFunilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eva': {
      id: '/_authenticated/eva'
      path: '/eva'
      fullPath: '/eva'
      preLoaderRoute: typeof AuthenticatedEvaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresas': {
      id: '/_authenticated/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof AuthenticatedEmpresasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/disparos': {
      id: '/_authenticated/disparos'
      path: '/disparos'
      fullPath: '/disparos'
      preLoaderRoute: typeof AuthenticatedDisparosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cadencias': {
      id: '/_authenticated/cadencias'
      path: '/cadencias'
      fullPath: '/cadencias'
      preLoaderRoute: typeof AuthenticatedCadenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/': {
      id: '/_authenticated/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof AuthenticatedCrmIndexRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/$id': {
      id: '/_authenticated/crm/$id'
      path: '/$id'
      fullPath: '/crm/$id'
      preLoaderRoute: typeof AuthenticatedCrmIdRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meta/webhook': {
      id: '/api/public/meta/webhook'
      path: '/api/public/meta/webhook'
      fullPath: '/api/public/meta/webhook'
      preLoaderRoute: typeof ApiPublicMetaWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/campaign-run': {
      id: '/api/public/hooks/campaign-run'
      path: '/api/public/hooks/campaign-run'
      fullPath: '/api/public/hooks/campaign-run'
      preLoaderRoute: typeof ApiPublicHooksCampaignRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/cadence-run': {
      id: '/api/public/hooks/cadence-run'
      path: '/api/public/hooks/cadence-run'
      fullPath: '/api/public/hooks/cadence-run'
      preLoaderRoute: typeof ApiPublicHooksCadenceRunRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedCrmRouteChildren {
  AuthenticatedCrmIdRoute: typeof AuthenticatedCrmIdRoute
  AuthenticatedCrmIndexRoute: typeof AuthenticatedCrmIndexRoute
}

const AuthenticatedCrmRouteChildren: AuthenticatedCrmRouteChildren = {
  AuthenticatedCrmIdRoute: AuthenticatedCrmIdRoute,
  AuthenticatedCrmIndexRoute: AuthenticatedCrmIndexRoute,
}

const AuthenticatedCrmRouteWithChildren =
  AuthenticatedCrmRoute._addFileChildren(AuthenticatedCrmRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedCadenciasRoute: typeof AuthenticatedCadenciasRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRouteWithChildren
  AuthenticatedDisparosRoute: typeof AuthenticatedDisparosRoute
  AuthenticatedEmpresasRoute: typeof AuthenticatedEmpresasRoute
  AuthenticatedEvaRoute: typeof AuthenticatedEvaRoute
  AuthenticatedFunilRoute: typeof AuthenticatedFunilRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedTarefasRoute: typeof AuthenticatedTarefasRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedWhatsappRoute: typeof AuthenticatedWhatsappRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedCadenciasRoute: AuthenticatedCadenciasRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRouteWithChildren,
  AuthenticatedDisparosRoute: AuthenticatedDisparosRoute,
  AuthenticatedEmpresasRoute: AuthenticatedEmpresasRoute,
  AuthenticatedEvaRoute: AuthenticatedEvaRoute,
  AuthenticatedFunilRoute: AuthenticatedFunilRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedTarefasRoute: AuthenticatedTarefasRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedWhatsappRoute: AuthenticatedWhatsappRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AssinaturaRoute: AssinaturaRoute,
  AuthRoute: AuthRoute,
  PoliticaRoute: PoliticaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicHooksCadenceRunRoute: ApiPublicHooksCadenceRunRoute,
  ApiPublicHooksCampaignRunRoute: ApiPublicHooksCampaignRunRoute,
  ApiPublicMetaWebhookRoute: ApiPublicMetaWebhookRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
