/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedWhatsappRouteImport } from './routes/_authenticated/whatsapp'
import { Route as AuthenticatedTarefasRouteImport } from './routes/_authenticated/tarefas'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedFunilRouteImport } from './routes/_authenticated/funil'
import { Route as AuthenticatedEvaRouteImport } from './routes/_authenticated/eva'
import { Route as AuthenticatedEmpresasRouteImport } from './routes/_authenticated/empresas'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedCrmIndexRouteImport } from './routes/_authenticated/crm.index'
import { Route as AuthenticatedCrmIdRouteImport } from './routes/_authenticated/crm.$id'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWhatsappRoute = AuthenticatedWhatsappRouteImport.update({
  id: '/_authenticated/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTarefasRoute = AuthenticatedTarefasRouteImport.update({
  id: '/_authenticated/tarefas',
  path: '/tarefas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/_authenticated/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFunilRoute = AuthenticatedFunilRouteImport.update({
  id: '/_authenticated/funil',
  path: '/funil',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEvaRoute = AuthenticatedEvaRouteImport.update({
  id: '/_authenticated/eva',
  path: '/eva',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEmpresasRoute = AuthenticatedEmpresasRouteImport.update({
  id: '/_authenticated/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/_authenticated/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/_authenticated/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/_authenticated/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCrmIndexRoute = AuthenticatedCrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedCrmRoute,
} as any)
const AuthenticatedCrmIdRoute = AuthenticatedCrmIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedCrmRoute,
} as any)

export interface FileRoutesByFullPath {
  '/agenda': typeof AuthenticatedAgendaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/crm': typeof AuthenticatedCrmRouteWithChildren
  '/empresas': typeof AuthenticatedEmpresasRoute
  '/eva': typeof AuthenticatedEvaRoute
  '/funil': typeof AuthenticatedFunilRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/': typeof AuthenticatedIndexRoute
  '/crm/$id': typeof AuthenticatedCrmIdRoute
  '/crm/': typeof AuthenticatedCrmIndexRoute
}
export interface FileRoutesByTo {
  '/agenda': typeof AuthenticatedAgendaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/empresas': typeof AuthenticatedEmpresasRoute
  '/eva': typeof AuthenticatedEvaRoute
  '/funil': typeof AuthenticatedFunilRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/': typeof AuthenticatedIndexRoute
  '/crm/$id': typeof AuthenticatedCrmIdRoute
  '/crm': typeof AuthenticatedCrmIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRouteWithChildren
  '/_authenticated/empresas': typeof AuthenticatedEmpresasRoute
  '/_authenticated/eva': typeof AuthenticatedEvaRoute
  '/_authenticated/funil': typeof AuthenticatedFunilRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/tarefas': typeof AuthenticatedTarefasRoute
  '/_authenticated/whatsapp': typeof AuthenticatedWhatsappRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/crm/$id': typeof AuthenticatedCrmIdRoute
  '/_authenticated/crm/': typeof AuthenticatedCrmIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/agenda'
    | '/configuracoes'
    | '/crm'
    | '/empresas'
    | '/eva'
    | '/funil'
    | '/historico'
    | '/tarefas'
    | '/whatsapp'
    | '/'
    | '/crm/$id'
    | '/crm/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/agenda'
    | '/configuracoes'
    | '/empresas'
    | '/eva'
    | '/funil'
    | '/historico'
    | '/tarefas'
    | '/whatsapp'
    | '/'
    | '/crm/$id'
    | '/crm'
  id:
    | '__root__'
    | '/_authenticated/agenda'
    | '/_authenticated/configuracoes'
    | '/_authenticated/crm'
    | '/_authenticated/empresas'
    | '/_authenticated/eva'
    | '/_authenticated/funil'
    | '/_authenticated/historico'
    | '/_authenticated/tarefas'
    | '/_authenticated/whatsapp'
    | '/_authenticated/'
    | '/_authenticated/crm/$id'
    | '/_authenticated/crm/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRouteWithChildren
  AuthenticatedEmpresasRoute: typeof AuthenticatedEmpresasRoute
  AuthenticatedEvaRoute: typeof AuthenticatedEvaRoute
  AuthenticatedFunilRoute: typeof AuthenticatedFunilRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedTarefasRoute: typeof AuthenticatedTarefasRoute
  AuthenticatedWhatsappRoute: typeof AuthenticatedWhatsappRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/whatsapp': {
      id: '/_authenticated/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AuthenticatedWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tarefas': {
      id: '/_authenticated/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof AuthenticatedTarefasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/funil': {
      id: '/_authenticated/funil'
      path: '/funil'
      fullPath: '/funil'
      preLoaderRoute: typeof AuthenticatedFunilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/eva': {
      id: '/_authenticated/eva'
      path: '/eva'
      fullPath: '/eva'
      preLoaderRoute: typeof AuthenticatedEvaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/empresas': {
      id: '/_authenticated/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof AuthenticatedEmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/crm/': {
      id: '/_authenticated/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof AuthenticatedCrmIndexRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/$id': {
      id: '/_authenticated/crm/$id'
      path: '/$id'
      fullPath: '/crm/$id'
      preLoaderRoute: typeof AuthenticatedCrmIdRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
  }
}

interface AuthenticatedCrmRouteChildren {
  AuthenticatedCrmIdRoute: typeof AuthenticatedCrmIdRoute
  AuthenticatedCrmIndexRoute: typeof AuthenticatedCrmIndexRoute
}

const AuthenticatedCrmRouteChildren: AuthenticatedCrmRouteChildren = {
  AuthenticatedCrmIdRoute: AuthenticatedCrmIdRoute,
  AuthenticatedCrmIndexRoute: AuthenticatedCrmIndexRoute,
}

const AuthenticatedCrmRouteWithChildren =
  AuthenticatedCrmRoute._addFileChildren(AuthenticatedCrmRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRouteWithChildren,
  AuthenticatedEmpresasRoute: AuthenticatedEmpresasRoute,
  AuthenticatedEvaRoute: AuthenticatedEvaRoute,
  AuthenticatedFunilRoute: AuthenticatedFunilRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedTarefasRoute: AuthenticatedTarefasRoute,
  AuthenticatedWhatsappRoute: AuthenticatedWhatsappRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
